# Application bindings
$terminal = uwsm app -- ghostty
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory=$(omarchy-cmd-terminal-cwd)
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER ALT, B, Browser (private), exec, $browser --private
bindd = SUPER, S, Music, exec, uwsm app -- spotify
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER , Z, Zed, exec, $terminal -e zeditor
bindd = SUPER SHIFT, T, Activity, exec, $terminal -e btop
bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, S, Signal, exec, omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, P, Passwords, exec, uwsm app -- passmenu --type 


bindd = SUPER SHIFT, H, Manual, exec, omarchy-launch-webapp "https://manuals.omamix.org/2/the-omarchy-manual"
bindd = SUPER, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, Z, Z.AI, exec, omarchy-launch-webapp "https://z.ai"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com"
bindd = SUPER, M, Chat, exec, omarchy-launch-webapp "https://chat.google.com"
bindd = SUPER, E, Email, exec, uwsm app -- evolution
bindd = SUPER, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, M, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, L, LiveBook, exec, omarchy-launch-or-focus-webapp "LiveBook" "https://livebook.ferrao.dev"
bindd = SUPER, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"
bindd = SUPER SHIFT, W, Waybar Reload, exec, waybar-config

bindd = SUPER, bracketleft, Workspace backward, workspace, m-1
bindd = SUPER, bracketright, Workspace forward, workspace, m+1

bindd = ALT, up, Brightness Up, exec, ext-monitor-brightness up 
bindd = ALT, down, Brightness Down, exec, ext-monitor-brightness down

bindd = SUPER SHIFT, S, Toggle split, togglesplit, # dwindle
bindd = SUPER, slash, Show key bindings, exec, omarchy-menu-keybindings

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, Space
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu
unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L

# Move focus with CTRL + vim naviation 
# instead of default SUPER + arrwos 
unbind = SUPER, left
unbind = SUPER, right
unbind = SUPER, up
unbind = SUPER, down

bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d
